INSERT INTO exercises(user_id, name) VALUES ('1', 'squat');
INSERT INTO exercises(user_id, name) VALUES ('1', 'chest press');
INSERT INTO exercises(user_id, name) VALUES ('1', 'deadlift');
INSERT INTO exercises(user_id, name) VALUES ('1', 'leg press');
INSERT INTO exercises(user_id, name) VALUES ('1', 'overhead press');
INSERT INTO exercises(user_id, name) VALUES ('1', 'biceps arm curl');
INSERT INTO exercises(user_id, name) VALUES ('1', 'tricep pushdown');
INSERT INTO exercises(user_id, name) VALUES ('1', 'seated cable row');
INSERT INTO exercises(user_id, name) VALUES ('1', 'lat pulldown');
INSERT INTO exercises(user_id, name) VALUES ('1', 'preacher curls');
INSERT INTO exercises(user_id, name) VALUES ('1', 'hamstring curls');
INSERT INTO exercises(user_id, name) VALUES ('1', 'skull crushers');
INSERT INTO exercises(user_id, name) VALUES ('1', 'calf raises');
