INSERT INTO exercises(user_id, name) VALUES ('2', 'squat');
INSERT INTO exercises(user_id, name) VALUES ('2', 'chest press');
INSERT INTO exercises(user_id, name) VALUES ('2', 'deadlift');
INSERT INTO exercises(user_id, name) VALUES ('2', 'leg press');
INSERT INTO exercises(user_id, name) VALUES ('2', 'overhead press');
INSERT INTO exercises(user_id, name) VALUES ('2', 'biceps arm curl');
INSERT INTO exercises(user_id, name) VALUES ('2', 'tricep pushdown');
INSERT INTO exercises(user_id, name) VALUES ('2', 'seated cable row');
INSERT INTO exercises(user_id, name) VALUES ('2', 'lat pulldown');
INSERT INTO exercises(user_id, name) VALUES ('2', 'preacher curls');
INSERT INTO exercises(user_id, name) VALUES ('2', 'hamstring curls');
INSERT INTO exercises(user_id, name) VALUES ('2', 'skull crushers');
INSERT INTO exercises(user_id, name) VALUES ('2', 'calf raises');
