INSERT INTO exercises(name) VALUES ('bench press');
INSERT INTO exercises(name) VALUES ('chest flys');
INSERT INTO exercises(name) VALUES ('incline press');
INSERT INTO exercises(name) VALUES ('decline Press');
INSERT INTO exercises(name) VALUES ('dumbbell press');
INSERT INTO exercises(name) VALUES ('military press');
INSERT INTO exercises(name) VALUES ('deadlift');
INSERT INTO exercises(name) VALUES ('barbell squat');
INSERT INTO exercises(name) VALUES ('dumbbell curls');
INSERT INTO exercises(name) VALUES ('preacher curls');
INSERT INTO exercises(name) VALUES ('barbell row');
INSERT INTO exercises(name) VALUES ('tricep extensions');
INSERT INTO exercises(name) VALUES ('calf raises');
